version: "3.8"
services:
    likefeature:
        build:
            context: ./
            dockerfile: Src/Api/Dockerfile
        ports:
            - "8000:80"
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "P@55word"
            ACCEPT_EULA: "Y"
        ports:
            - 1434:1434